### ISSUE TITLE
iAP Bluetooth Connectivity Drops

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#1261]
### Bug Report
When connecting an iOS device with > 10 SDL apps to SYNC 3.2v2 via Bluetooth, a few errors appear:
1) App displays on sync but does not populate when going from NONE to FULL state
2) App does not show up at all on SYNC and iAP gets disconnected for that app
3) All > 10 apps do not appear on SYNC

##### Reproduction Steps
1. Create SDL enabled app
2. Pair the iOS device to SYNC via bluetooth

##### Expected Behavior
All apps should display and work properly

##### Observed Behavior
Sometimes App does not display on SYNC
Sometimes App does not work when tapped on SYNC (no RPCs received by SYNC)

##### OS & Version Information
* iOS Version: 12.2
* SDL iOS Version: 6.2.0
* Testing Against: SYNC 3.4 19126_DEVTEST

**Comment by joeljfischer** [comment]
If this issue only appears when 10+ apps are connected, it is hard to understand how this could be an iOS library related issue. Based on that information alone, it would almost certainly be a module-side issue. The iOS library doesn't do anything different when 1 app is connected compared to 10. Can you provide more information that makes it clear that this is a library-side issue?

**Comment by NicoleYarroch** [comment]
@SatbirTanda Were the apps being tested using the multisession protocol, unique protocol strings or a mix of both?

**Comment by NicoleYarroch** [comment]
> App displays on sync but does not populate when going from NONE to FULL state

Does this mean the when the SDL app icon is tapped the SDL app does not open, or that the SDL app opens but the screen is empty?

**Comment by SatbirTanda** [comment]
@NicoleYarroch - The latter, the SDL app opens up but the default template shows.  Also, the apps were a mix of both (some used the multisession string and some did not).

**Comment by NicoleYarroch** [comment]
@SatbirTanda 
For your first bug I noticed something similar while testing with SYNC 3.4 Build 19126_DEVTEST

TDK version: SYNC 3, v.3.4, Build 19126_DEVTEST
Phone: iPhone XS Max iOS v.12.1.4

## Bug Report
1. Connect app to TDK using Bluetooth transport.
2. Open the SDL app.
3. Connect the phone to the TDK using a USB cord.
4. Wait for app icon to show up in the TDK's "Apps" tab. Select the app icon.

### Expected Result
An `OnHMIStatus` notification should be sent by Core notifying the app that the SDL app now has a `hmiLevel` of `FULL. Since no notification is sent, the app does not send a `Show` RPC to populate the screen.

### Actual Result
No `OnHMIStatus` notification is sent by Core. I have to put the SDL app in the background and then foreground it again before I get a `OnHMIStatus` notification.

**Comment by NicoleYarroch** [comment]
The first bug could also be caused by #1264

**Comment by SatbirTanda** [comment]
It looks like there's a case where SDL attempts to create a session before the EAAccessory is connected, which leads to a one connection attempt to go to waste and occasionally a failure to ever pick up the Accessory.  It always gets logged out as null too.  Attached is a log showing failure to pick up accessory on first try, connecting to SYNC with RAI response, then a disconnect.  This log displays issue 1 of the original post, the app displays on sync, does not populate the template when tapped, gets disconnected, but does not get removed from HMI.
[App_Connects_then_no_template.txt](https://github.com/smartdevicelink/sdl_ios/files/3229649/App_Connects_then_no_template.txt)

**Comment by SatbirTanda** [comment]
Can confirm we are seeing these issues if only one SDL app in on the phone

**Comment by NicoleYarroch** [comment]
@SatbirTanda I believe the race conditions in setting up a session when switching between BT and USB were fixed in PR #1248. If not, please reopen the issue.

**Comment by SatbirTanda** [comment]
Hey @NicoleYarroch this issue is primarily seen on a a plain BT connection to a HU.  (No transport switching)

**Comment by NicoleYarroch** [comment]
@SatbirTanda We fixed a number of race conditions that were introduced because there is a SDL available accessory connected when the current transport disconnects (i.e. if the USB transport is destroyed, the accessory is still connected over BT) This meant that sessions would be created but then destroyed (without the proper shut-down) by the lifecycle manager. This lead to SDL apps showing up on the head unit but since the session was destroyed on the app side no communication could happen. Not sure why core doesn't detect that a session was destroyed. 

I would suggest testing the PR #1248 and see if it fixes the issue.

**Comment by SatbirTanda** [comment]
Yes, I integrated this develop branch into my cocoa pod and tested, still seeing the app not appearing over BT in cases

**Comment by NicoleYarroch** [comment]
@SatbirTanda Are you still seeing sessions being destroyed in your logs or is it just an `EAAccessoryManager` empty accessory list issue?

**Comment by SatbirTanda** [comment]
I see the accessory get printed out as (null) and also I see that a session try to get created before the accessory is picked up.  In SDLProxy.m I see
```objc
        [self.transport connect];

        SDLLogV(@"Proxy transport initialization");
        [[EAAccessoryManager sharedAccessoryManager] registerForLocalNotifications];
```
where connect is called before `registerForLocalNotifications` but I see that ` [[EAAccessoryManager sharedAccessoryManager] registerForLocalNotifications]` is written twice

**Comment by stefanek22** [comment]
@NicoleYarroch can this issue be reopened, per Satbir's comments?  The underlying issue is still seen...

**Comment by NicoleYarroch** [comment]
@SatbirTanda, @stefanek22 I created a new issue: #1316 and PR #1317 that I think fixes the issue of the session not being created.
